# Generated by Django 3.0 on 2019-12-11 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idx', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_obsolete', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('phone2', models.CharField(blank=True, max_length=15, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('staff', 'staff'), ('moderator', 'moderator'), ('other', 'other')], max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('profile_pic', models.ImageField(upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, max_length=60)),
                ('country', models.CharField(choices=[('USA', 'USA'), ('China', 'China'), ('Russia', 'Russia'), ('China', 'China'), ('India', 'India'), ('Nepal', 'Nepal')], default='Nepal', max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('account_name', models.CharField(max_length=20)),
                ('created_by', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('open', 'open'), ('close', 'close')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'User_Account',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('status_choice', models.TextField(blank=True, choices=[('New', 'New'), ('In_Progress', 'In_Progress'), ('Completed', 'Completed')], max_length=15)),
                ('priority_choice', models.TextField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=15)),
                ('created_by', models.CharField(max_length=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(verbose_name=django.utils.timezone.now)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice1', models.TextField(blank=True, max_length=200)),
                ('notice2', models.TextField(blank=True, max_length=200)),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Account')),
            ],
            options={
                'verbose_name_plural': 'Notice',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=120)),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.Account')),
            ],
        ),
    ]
